# Generated by Django 3.0.8 on 2020-07-24 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20200724_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreport',
            name='report',
        ),
    ]
