# Generated by Django 3.0.8 on 2020-08-27 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_remove_userreport_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentreport',
            name='report',
        ),
    ]
