# Generated by Django 3.0.8 on 2020-07-22 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200722_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfollowing',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='userfollowing',
            unique_together={('user', 'to_follow')},
        ),
        migrations.RemoveField(
            model_name='userfollowing',
            name='current_user',
        ),
    ]
