# Generated by Django 3.0.8 on 2020-07-22 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200722_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfollowing',
            name='following_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='userfollowing',
            unique_together={('user', 'following_user')},
        ),
        migrations.RemoveField(
            model_name='userfollowing',
            name='to_follow',
        ),
    ]
