# Generated by Django 3.0.8 on 2020-08-28 06:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('relationships', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfollowing',
            old_name='following_user',
            new_name='followee',
        ),
        migrations.RenameField(
            model_name='userfollowing',
            old_name='user',
            new_name='follower',
        ),
        migrations.AlterUniqueTogether(
            name='userfollowing',
            unique_together={('follower', 'followee')},
        ),
    ]
