# Generated by Django 3.0.8 on 2020-07-20 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netizen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='description',
        ),
        migrations.RemoveField(
            model_name='template',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='template',
            name='user',
        ),
    ]
