# Generated by Django 3.0.8 on 2020-07-20 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netizen', '0003_auto_20200720_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='images',
            field=models.ImageField(upload_to='media/templates'),
        ),
    ]
