# Generated by Django 3.0.8 on 2020-07-23 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netizen', '0007_auto_20200721_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='images',
            field=models.ImageField(upload_to='netizen/memes'),
        ),
        migrations.AlterField(
            model_name='meme',
            name='thumbnail',
            field=models.ImageField(default='hi', upload_to='netizen/memes/thumbs'),
        ),
        migrations.AlterField(
            model_name='template',
            name='images',
            field=models.ImageField(upload_to='netizen/templates'),
        ),
        migrations.AlterField(
            model_name='template',
            name='thumbnail',
            field=models.ImageField(default='hi', upload_to='netizen/templates/thumbs'),
        ),
    ]
