# Generated by Django 3.0.8 on 2020-08-31 06:04

from django.db import migrations, models
import django.db.models.deletion
import netizen.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('netizen', '0008_auto_20200723_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='images',
        ),
        migrations.RemoveField(
            model_name='template',
            name='thumbnail',
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('images', models.ImageField(upload_to=netizen.models.get_template_images_path)),
                ('thumbnail', models.ImageField(default='hi', upload_to=netizen.models.get_template_thumbnail_path)),
                ('template', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='netizen.Template')),
            ],
        ),
    ]
