# Generated by Django 3.0.8 on 2020-08-31 06:58

from django.db import migrations, models
import django.db.models.deletion
import netizen.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('netizen', '0009_auto_20200831_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('images', models.ImageField(upload_to=netizen.models.get_template_images_path)),
                ('thumbnail', models.ImageField(default='hi', upload_to=netizen.models.get_template_thumbnail_path)),
                ('object_id', models.UUIDField(editable=False)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.RemoveField(
            model_name='meme',
            name='images',
        ),
        migrations.RemoveField(
            model_name='meme',
            name='thumbnail',
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
