# Generated by Django 3.0.8 on 2020-09-12 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netizen', '0011_auto_20200831_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='description',
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
